#!/bin/bash

HOME=/home/vsouza
DIR=$(pwd)
cd /tmp/

command_exists() {
    command -v "$1" &> /dev/null ;
}

# installing google chrome
printf "\n\ninstalling google chrome\n"
if ! command_exists google-chrome-stable; then
    sudo aptitude install -y libappindicator1
    if [ ! -f google-chrome-stable_current_amd64.deb ]; then
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    fi
    sudo dpkg -i google-chrome-stable_current_amd64.deb
fi
printf "done\n"

# installing git
printf "\n\ninstalling git\n"
if ! command_exists git; then
    sudo apt-get install -y git
    git config --global user.name "Vitor de Souza"
    git config --global user.email "vitor_souza@outlook.com"
    git config --global push.default simple
fi
printf "done\n"

# installing vim, gvim and related
printf "\n\ninstalling vim and related\n"
if ! command_exists vim; then
    sudo apt-get -y install vim vim-gnome
fi
if [ ! -d $HOME/.vim/bundle/Vundle.vim ]; then
    git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
fi
cd $HOME
if [ ! -d $HOME/.git ]; then
    git init
    git remote add origin git@github.com:vsouz4/dotfiles.git
    git fetch origin
    git reset --hard origin/master
fi

vim +PluginInstall +qall

# custom vim snippets
printf "\n\ninstalling custom vim snippets"
if [ ! -d $HOME/.vim/UltiSnips ]; then
    git clone git@github.com:vsouz4/vim-snippets.git $HOME/.vim/UltiSnips
fi

# installing tmux and other bash stuff
printf "\n\ninstalling tmux and other bash stuff"
if ! command_exists zsh; then
    sudo apt-get install -y terminator tmux zsh fonts-powerline
    sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
    git reset --hard origin/master
    touch alias.zsh
fi

# installing some extra stuff
printf "\n\ninstalling some extra stuff\n"
if ! command_exists xclip; then
    sudo apt-get install -y xclip curl build-essential fonts-font-awesome
fi

# installing i3
printf "\n\ninstalling i3\n"
if ! command_exists dmenu; then
    sudo apt-get install -y i3 i3status dmenu i3lock xbacklight feh conky
fi
printf "done\n"

# installing docker
printf "\n\ninstalling docker\n"
if ! command_exists docker; then
    sudo apt-get install -y apt-transport-https ca-certificates software-properties-common
    curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
    sudo apt-get update
    sudo apt-get install docker-ce
    sudo groupadd docker
    sudo usermod -aG docker $USER
    sudo docker run hello-world
fi
if ! command_exists docker-compose; then
    sudo apt-get install python-setuptools
    sudo easy_install pip
    sudo pip install docker-compose
fi
printf "done\n"

# configuring i3blocks
if ! command_exists i3blocks; then
    cd /tmp/
    git clone git://github.com/vivien/i3blocks
    cd i3blocks
    make clean debug
    sudo make install
fi

# go back
cd $DIR
